#***************************************************************************
# This file contains code for blue LED blinking. This function is called from nodered 
# when an unauthorized car is parked in reserved parking.  
# generated by ultrasonic ranger 
# Author: Group1 - Deepthi Warrier, Tejashri Joshi
# Date: 16-March-2020
#*************************************************************************
# import the GrovePi+ libraries
from grovepi import *
import time

redled_ps3 = 3
pinMode(redled_ps3,"OUTPUT")

if __name__ == '__main__':
	try:
		count = 0
		# logic to blink the LED for 10 counts
		while(count <= 10):
			digitalWrite(redled_ps3,1)
			time.sleep(0.5)
			digitalWrite(redled_ps3, 0)
			time.sleep(0.5)
			count+= 1 
		digitalWrite(redled_ps3,1)
	except Exception as ex:
		print('An Exception occured %s' % ex)
