#***************************************************************************
# This file controls the functioning of motor to open gate based on output 
# generated by ultrasonic ranger 
# Author: Group1 - Deepthi Warrier, Tejashri Joshi
# Date: 16-March-2020
#*************************************************************************
import RPi.GPIO as GPIO
import time
from grovepi import *

#Global Variables
GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.OUT)
pwm = GPIO.PWM(18, 50)
pwm.start(0)

ultrasonic_ranger = 4
pinMode(ultrasonic_ranger,"INPUT")
# sets the angle of rotation for motor
def setAngle(angle):
	duty = angle/10.0+2.5;
	pwm.ChangeDutyCycle(duty)	
	
if __name__ == '__main__':
	try:
		# if car is at distance of less than 5 motor will move up and down to open gate
		car_distance = ultrasonicRead(ultrasonic_ranger)
		print("car distance:"+str(car_distance))
		
		if (car_distance < 5):
			# Set the angle to open the gate
			setAngle(150)	
			time.sleep(0.5)
			pwm.stop()

			# Open the gate for 5 seconds
			time.sleep(5)

			# Set the angle to close the gate
			pwm.start(0)			
			setAngle(75)
			time.sleep(0.5)	
	except KeyboardInterrupt:
		print("Exiting")
		pwm.stop()
		GPIO.cleanup()	
	except IOError:
		print("IOError Occured")
		pwm.stop()
		GPIO.cleanup()		
	except Exception as ex:
		print('An error has occurred: %s' % ex)
		pwm.stop()
		GPIO.cleanup()

	pwm.stop()
	GPIO.cleanup()
		
	

