#***************************************************************************
# This file contains code to turn on the blue LED. This function is called from nodered. 
# when user reserves parking spot we need to turn ON the blue LED.  
# generated by ultrasonic ranger 
# Author: Group1 - Deepthi Warrier, Tejashri Joshi
# Date: 16-March-2020
#*************************************************************************
# import the GrovePi+ libraries
from grovepi import *
import time

blueled_ps3 = 3

pinMode(redled_ps3,"OUTPUT")

if __name__ == '__main__':
	try:
			digitalWrite(blueled_ps3,1)
	except Exception as ex:
		print('An Exception occured %s' % ex)
